### ISSUE TITLE
Invalid amount and currency for operations with contracts

### ISSUE THREAD

**Issue by ralexandr** [tronprotocol/tron-rosetta-api#11]
If i try to fetch transaction with contract-transfers, i receive invalid amount and currency

### /block/transaction

Request:

`
{
  "network_identifier": {
    "blockchain": "tron",
    "network": "mainnet"
  },
  "block_identifier": {
    "index": 1969253,
    "hash": "00000000001e0c6570f68a69bf6c0535c4281f412c1f98794f26d946ebcdaf3d"
  },
  "transaction_identifier": {
    "hash": "7853e948d1409c92baaed45d60472f13aca047eee31cd36410a907e0493333b8"
  }
}
`

Response:
`
{
    "transaction": {
        "transaction_identifier": {
            "hash": "7853e948d1409c92baaed45d60472f13aca047eee31cd36410a907e0493333b8"
        },
        "operations": [
            {
                "operation_identifier": {
                    "index": 0
                },
                "type": "TransferAssetContract",
                "status": "SUCCESS",
                "account": {
                    "address": "TWxezzaF6Lyvh4mNVQRj9okro8hqC3LfJt"
                },
                "amount": {
                    "value": "-2170",
                    "currency": {
                        "symbol": "TRX",
                        "decimals": 6
                    }
                }
            },
            {
                "operation_identifier": {
                    "index": 1
                },
                "type": "TransferAssetContract",
                "status": "SUCCESS",
                "account": {
                    "address": "TLsV52sRDL79HXGGm9yzwKibb6BeruhUzy"
                },
                "amount": {
                    "value": "2170",
                    "currency": {
                        "symbol": "TRX",
                        "decimals": 6
                    }
                }
            }
        ]
    }
}
`

Same transaction on tronscan.org: https://tronscan.org/#/transaction/7853e948d1409c92baaed45d60472f13aca047eee31cd36410a907e0493333b8

**Comment by Yrp** [comment]
Hi, man. Only supports retrieval of account balances

**Comment by ralexandr** [comment]
> Hi, man. Only supports retrieval of account balances

Are there any plans to support full list of endpoints listed in rosetta-api specification?

**Comment by ralexandr** [comment]
> Hi, man. Only supports retrieval of account balances

Does it mean that currently there is no way to fetch token-transaction with tron-rosetta-api ?
And are there any plans to implement that?

**Comment by Yrp** [comment]
> > Hi, man. Only supports retrieval of account balances
> 
> Does it mean that currently there is no way to fetch token-transaction with tron-rosetta-api ?
> And are there any plans to implement that?

Not yet.
