### ISSUE TITLE
Initial synchronization is very slow

### ISSUE THREAD

**Issue by alecalve** [tronprotocol/tron-rosetta-api#12]
We've been running a node (`1.0.0`) for a few weeks now. It is still not synced and is now only processing less than 2,500 blocks per hour.

The machine it's running on is performant (SSD and ample CPU/RAM). Is there any configuration changes that would help with improving the speed?

**Comment by Yrp** [comment]
At some point in history, the block had many transactions and these transactions were executed over a long period of time. So syncing blocks can be slow. What block height are you syncing to now?

**Comment by alecalve** [comment]
Right now it is processing data as of around block 10,150,000.

**Comment by alecalve** [comment]
For reference, here's the history of the node's height over time
<img width="970" alt="image" src="https://user-images.githubusercontent.com/3832610/94440318-d9c71f00-01a1-11eb-96c7-6870205fb571.png">

**Comment by Yrp** [comment]
Using the Concurrent Mark Sweep (CMS) Collector or G1 Collector may improve performance!

**Comment by Yrp** [comment]
Using the Concurrent Mark Sweep (CMS) Collector or G1 Collector may improve performance!

**Comment by Yrp** [comment]
The curve looks normal.
