### ISSUE TITLE
API doesn't work when using a snapshot

### ISSUE THREAD

**Issue by alecalve** [tronprotocol/tron-rosetta-api#18]
We downloaded an node snapshot from http://47.89.178.46/ and replaced our node's database with it.

Rosetta endpoints do not work with such a setup:

```
$  rosetta-cli view:block 1
... request failed: /block request failed: /block {Code:100 Message:error:block balance info not find Retriable:false Details:map[]}
```

Is this expected? Is there anyway to use snapshots _and_ Tron Rosetta API?

**Comment by Yrp** [comment]
This snapshot does not contain rosetta data. The rosetta APIs require a proprietary database.  And there are no plans to offer it for now. Sorry about it.

**Comment by alecalve** [comment]
Ok, thanks for the feedback!
