### ISSUE TITLE
Linkable operations should be linked

### ISSUE THREAD

**Issue by alecalve** [tronprotocol/tron-rosetta-api#7]
In its current form, the Tron Rosetta API doesn't link operations together. The Rosetta spec enables this however, via the `related_operations` field.

Adding this information would remove possible ambiguity for operations with more than 2 balance updates.

If in a transaction, Alice sends Bob 1 TRX and Charlie sends Doug 1 TRX, one will get from the API:

Alice -1 TRX
Bob +1 TRX
Charlie -1 TRX
Doug +1 TRX

This could be interpreted as either (Alice -> Bob and Charlie -> Doug) or (Alice -> Doug and Bob -> Charlie).

**Comment by Yrp** [comment]
this `related_operations` field is optional via the url https://www.rosetta-api.org/docs/models/Operation.html
