### ISSUE TITLE
/account/balance returns incorrect balances

### ISSUE THREAD

**Issue by alecalve** [tronprotocol/tron-rosetta-api#8]
For address TQq3TQB7CA37AJAJrnZbhzLgn3TthY4teE:

1. it received 1 TRX at block 319,185
2. it froze that 1 TRX at block 319,189

Using `tron-rosetta-api` at commit 870c620c208a09a243598a36334a1351760600c2, I get the following balances:

| Height | Balance using rosetta-cli | Expected balance |
|--------|-------------------------:|-----------------: |
| 319,184 | 0 TRX | 0 TRX |
| 319,185 | 1 TRX | 1 TRX |
| ... | ... | ... |
| 319,189 | 1 TRX | 1 TRX |
| 319,190 | **1 TRX** | 0 TRX |

The freeze operation is visible when querying the block itself:

```json
 {
 	"operation_identifier": {
 		"index": 0
 	},
 	"type": "FreezeBalanceContract",
 	"status": "SUCCESS",
 	"account": {
 		"address": "TQq3TQB7CA37AJAJrnZbhzLgn3TthY4teE"
 	},
 	"amount": {
 		"value": "-1000000",
 		"currency": {
 			"symbol": "TRX",
 			"decimals": 6
 		}
 	}
 }
```

**Comment by Yrp** [comment]
Thanks for the feedback, I'll check it.

**Comment by Yrp** [comment]
I ran a rosetta-api node that synchronizes the tron mainnet. The data returned by this node is the expected result.

Height | Balance using rosetta-cli | Expected balance
-- | -- | --
319,184 | 0 TRX | 0 TRX
319,185 | 1 TRX | 1 TRX
... | ... | ...
319,189 | 0 TRX | 0 TRX
319,190 | 0 TRX | 0 TRX

This is a snapshot for calling endpoint /account/balance at block 319,189
![image](https://user-images.githubusercontent.com/1221572/90528770-94c4cb80-e1a5-11ea-9f9c-7f8d4883c4ea.png)

This is a snapshot for calling endpoint /block at block 319,189
![image](https://user-images.githubusercontent.com/1221572/90529030-d5244980-e1a5-11ea-9792-1069a3aa2712.png)

**Comment by alecalve** [comment]
hum, interesting. Could it be something related to the database changes not being persisted when the docker image is stopped?

**Comment by alecalve** [comment]
I'll try restarting from scratch and not interrupting the node

**Comment by alecalve** [comment]
Okay, so restarting it fixed this.

**Comment by Yrp** [comment]
The node won't destroy the database by killing processes through signals 9 and 15. It' s safe.
